In [4]:
import numpy as np      #accessing numpy
list=[1,2,3,4]
array=np.array(list)    #converting python list to numpy array
print(array)

[1 2 3 4]


In [10]:
x=np.array([2,3,4])
print(x)

[2 3 4]


In [5]:
array      #different from 'printing' array: comma separated elements

array([1, 2, 3, 4])

In [2]:
import numpy as np
array=np.array([1,2,3])    #np.ndim - gives the dimension of array
print(array.ndim)

1


In [3]:
print(array.itemsize)     #prints size of the datatype of each element in bytes

4


In [6]:
print(array.nbytes)      #np.nbytes - itemsize*no of elements

12


In [9]:
a=np.array([[1,2,3],[3,4,5]])
print(a[1,1])                   #to get a specific element: np.array(row,col) - they start from 0

4


In [10]:
print(a[:,1])   #to get a column

[2 4]


In [11]:
print(a[1,:])   #to get a row

[3 4 5]


In [12]:
a[0,2]=5
a[:,0]=[3,1]    
print(a)

[[3 2 5]
 [1 4 5]]


In [6]:
a=array+10    #performing arithmetic operations on array elements
print(a)

[11 12 13 14]


In [8]:
b=array*2
print(b)

[2 4 6 8]


In [9]:
c=array-5
print(c)

[-4 -3 -2 -1]


In [11]:
two_dimension_list=([1,2,3],            #two dimension array
                    [4,5,6])
print(np.array(two_dimension_list))

[[1 2 3]
 [4 5 6]]


In [12]:
three_dimension_list=([1,2],           #three dimension array
                       [3,4],
                       [5,6])
print(np.array(three_dimension_list))
                      

[[1 2]
 [3 4]
 [5 6]]


In [13]:
shape1=array.shape     #shape of the array 
                       #if one dimension then 'shape' prints its length(no of elements)
print(shape)

(4,)


In [17]:
a=([1,2,3],
   [4,5,6])           #shape-if 2 dimension, then it prints: no of rows,no of elements in each row
b=np.array(a)
shape1=b.shape
print(shape1)
   


(2, 3)


In [18]:
a=([1,3,4],
   [6,7,8,9])      #shape-if multi-dimensioned with unequal no of elements: consider array as on object(?)
b=np.array(a)
shape=b.shape
print(shape)


(2,)


<ipython-input-18-d38664508096>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array(a)


In [19]:
a=([1,2],
   [3,4],
   [5,6])
b=np.array(a)
shape=b.shape          #shape for 3 dimensional array
print(shape)


(3, 2)


In [32]:
a=([1.0,2.4,3.2],
   [5.6,7.8,9.0])

b=np.array(a)
data_type=b.dtype
print(data_type)     #dtype-specifies datatype 

float64


In [13]:
import numpy as np
a = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]            #3 dimension array-nested 3 arrays
])
print(a)
print(a.shape) #no of layers, no of rows in each layer, no of columns in each layer
print(a.dtype) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int32


In [14]:
import numpy as np
a=np.zeros((2,2))       #if datatype not specified: taken as float
print(a)


[[0. 0.]
 [0. 0.]]


In [19]:
import numpy as np
a=np.zeros((2,2),dtype=np.int16)   #dtype specified
print(a)

[[0 0]
 [0 0]]


In [22]:
import numpy as np
a=np.ones((3,2),dtype=np.float32)      #np.ones(rows,columns)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
print(a.shape)
print(a.dtype)

(3, 2)
float32


In [16]:
import numpy as np
print(np.full([2,2],36))    #to make an array with all same elements:np.full(shape,value)

[[36 36]
 [36 36]]


In [28]:
import numpy as np
a=([1,2,3],
   [4,5,6])
b=np.array(a)
c=b.reshape(3,2)           #transpose(give parameters accordingly)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(np.full_like(a,4))     #np.full_like : makes an array with same shape as mentioned

[[4 4 4]
 [4 4 4]]


In [29]:
b.flatten()       #flattened 2 dimensional array

array([1, 2, 3, 4, 5, 6])

In [36]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))       #stacks 2 separate arrays horizontally
print(c)


[1 2 3 4 5 6]


In [34]:
d=np.vstack((a,b))
print(d)

[[1 2 3]
 [4 5 6]]


In [37]:
#np.random.normal(loc,scale,size)


In [38]:
import numpy as np
a=np.arange(1,5)          #np.arrange(starting,end,difference between consecutive elements(default-1))
print(a)

[1 2 3 4]


In [39]:
a=np.arange(5,21,5)  
print(a)

[ 5 10 15 20]


In [41]:
import numpy as np
a=np.linspace(1,5,num=5,endpoint=True)       #np.linspace(starting no, end num, nums needed in sample, endpoint to be included or not)-evenly spaced sample
print(a)

[1. 2. 3. 4. 5.]


In [45]:
a=np.linspace(2.0,10.0,num=20)       #if endpoint not mentioned, endpoint=True
print(a)

[ 2.          2.42105263  2.84210526  3.26315789  3.68421053  4.10526316
  4.52631579  4.94736842  5.36842105  5.78947368  6.21052632  6.63157895
  7.05263158  7.47368421  7.89473684  8.31578947  8.73684211  9.15789474
  9.57894737 10.        ]


In [47]:
import numpy as np
a=np.logspace(2.0,3.0,num=2)         #np.logspace:same as linspace-but log values
print(a)

[ 100. 1000.]


In [48]:
###SLICING

In [49]:
import numpy as np
a=([1,2,3],
   [4,5,6],
   [7,8,9])  #slicing rows(starts from 0)
b=a[0]
print(b)


[1, 2, 3]


In [50]:
b=a[1]
print(b)

[4, 5, 6]


In [51]:
c=a[2]
print(c)

[7, 8, 9]


In [60]:
import numpy as np
a=([1,2,3],
   [4,5,6],
   [7,8,9])
b=(a[1,:2])
print(b)

TypeError: tuple indices must be integers or slices, not tuple

In [1]:
#Creating a random gaussian distribution
import numpy as np
array=np.random.normal(10,1,10)           #np.random.normal(loc,scale,size)
print(array)

[11.22586673 10.29486437  9.54672599  9.45521635 12.58673624  9.06504918
 10.49692691 10.34453106  9.06128514 10.58753023]


In [2]:
#statistical functions 
print(np.min(array))
print(np.max(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))


9.061285144616093
12.586736236002503
10.266473219649308
10.319697711614495
1.0266067288640408


In [3]:
import numpy as np
a=np.array([1,2,3])      #dot product of two 1D arrays-np.dot()
b=np.array([4,5,6])
dot_product=np.dot(a,b)
print(dot_product)

32


In [8]:
a=[[1,2],[4,5]]
b=[[3,2],[6,5]]
matrix_product=np.matmul(a,b)     #np.matmul()-performs matrix multiplication
print(matrix_product)

[[15 12]
 [42 33]]


In [9]:
matrix=np.array([[1,2],[3,4]])
print(matrix)
print("Determinant:",np.linalg.det(matrix))
print("inverse:",np.linalg.inv(matrix))
print("Rank:",np.linalg.matrix_rank(matrix))
eigenvalues,eigenvectors=np.linalg.eig(matrix)
print("Eigen values & eigen vectors:",eigenvalues,eigenvectors)
print("Diagonal of matrix:",matrix.diagonal())
print("Transpose of matrix",matrix.transpose())
print("Trace of matrix",matrix.trace())

[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Rank: 2
Eigen values & eigen vectors: [-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Diagonal of matrix: [1 4]
Transpose of matrix [[1 3]
 [2 4]]
Trace of matrix 5


In [20]:
print(np.random.rand(2,3))    #prints random decimals of the shape specified

[[0.70265753 0.78253896 0.95091207]
 [0.88214869 0.23830537 0.05985322]]


In [23]:
print(np.random.randint(-1,1,size=(2,1)))   #prints integers from specified range and shape

[[ 0]
 [-1]]


In [24]:
print(np.identity(4))    #prints identity matrix of specified order

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
a=[[1,2,3,4]]
array=np.array(a)                   #np.repeat(array,no of rows, axis of reference) - repeats that row specified no of times
final=np.repeat(array,4,axis=0)
print(final)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
